### ISSUE TITLE
Uncaught TypeError: e.stopPropagation is not a function

### ISSUE THREAD

**Issue by camlafit** [yubaoquan/tree-view-git-branch-fix#3]
Following #1 

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Debian GNU/Linux
**Thrown From**: [tree-view-git-branch-fix](https://github.com/yubaoquan/tree-view-git-branch-fix) package 0.3.6

### Stack Trace

Uncaught TypeError: e.stopPropagation is not a function

```
At /home/km/.atom/packages/tree-view-git-branch-fix/lib/branch-list.js:114

TypeError: e.stopPropagation is not a function
    at HTMLLIElement.toggleExpansion (/packages/tree-view-git-branch-fix/lib/branch-list.js:114:15)
    at TreeView.module.exports.TreeView.entryClicked (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:487:30)
    at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:228:32)
```

### Commands

```
```

### Non-Core Packages

```
adwaita-pro-ui 2.1.5 
atom-beautify 0.30.9 
atom-ide-ui 0.6.0 
docblockr 0.13.3 
ide-php 0.7.3 
project-viewer 1.2.5 
tree-view-git-branch-fix 0.3.6 
```

**Comment by yubaoquan** [comment]
OK, Added a logic to check if e has a stopPropagation method before call it.

But I don't know what action triggers this bug. 

Event objects should always have a stopPropagation method.

**Comment by camlafit** [comment]
Looks ok :)
